# Generated by Django 5.1.6 on 2025-03-29 05:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='последний вход')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Обозначает, что у этого пользователя есть все разрешения без явного их назначения.',
                                                     verbose_name='статус суперпользователя')),
                ('username', models.CharField(
                    error_messages={'unique': 'Пользователь с таким именем уже существует.'},
                    help_text='Обязательно. Не более 150 символов. Буквы, цифры и @/./+/-/_ только.',
                    max_length=150, unique=True,
                    validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                    verbose_name='имя пользователя'
                )),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='фамилия')),
                ('is_staff', models.BooleanField(default=False,
                                                 help_text='Обозначает, может ли пользователь входить на этот сайт администратора.',
                                                 verbose_name='статус персонала')),
                ('is_active', models.BooleanField(default=True,
                                                  help_text='Обозначает, следует ли считать этого пользователя активным. Снимите этот флажок вместо удаления аккаунтов.',
                                                  verbose_name='активный')),
                ('date_joined',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('groups', models.ManyToManyField(
                    blank=True,
                    help_text='Группы, к которым принадлежит этот пользователь. Пользователь получит все разрешения, предоставленные каждой из его групп.',
                    related_name='user_set', related_query_name='user',
                    to='auth.group', verbose_name='группы'
                )),
                ('user_permissions', models.ManyToManyField(
                    blank=True,
                    help_text='Конкретные разрешения для этого пользователя.',
                    related_name='user_set', related_query_name='user',
                    to='auth.permission', verbose_name='разрешения пользователя'
                )),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
