# Generated by Django 5.1.6 on 2025-03-14 05:01

import Students.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'ordering': ['group_name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=Students.models.get_default_group, on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='Students.group'),
        ),
    ]
