# Generated by Django 5.1.6 on 2025-04-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_student_email_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'permissions': [('can_promote_student', 'Can promote student'), ('can_expel_student', 'Can expel student')], 'verbose_name': 'студент', 'verbose_name_plural': 'студенты'},
        ),
    ]
